export const prewedding = {
  title: "Prewedding Photography",
  description: "Natural, elegant, and timeless moments that reflect your unique connection.",
  image: "3.webp",
  plans: [
    {
      type: "group",
      name: "Outdoors",
      notes: [
        "Harga belum termasuk akomodasi ke lokasi dan berbeda - beda setiap kota",
        "Harga belum termasuk akomodasi izin di lokasi",
      ],
      items: [
        {
          name: "Outdoors Premium",
          price: 1750000,
          features: [
            "Outdoor 1 Lokasi",
            "Mua profesional",
            "2 Photographer",
            "Wadrobe 1 gaun/kebaya",

            "1 Pembesaran 40x60 plus frame",
            "Semua file copy",
          ],
        },
        {
          name: "Outdoors Exlusive",
          price: 2300000,
          features: [
            "Outdoor 1 Lokasi",
            "Mua profesional",
            "2 Photographer",
            "Wadrobe 1 gaun/kebaya",
            "Free baju casual",

            "2 Pembesaran 40x60 plus frame",
            "Semua file copy",
          ],
        },
        {
          name: "Outdoors Gold",
          price: 3300000,
          features: [
            "Outdoor 2 lokasi berdekatan",
            "Mua profesional",
            "2 Photographer",
            "Wadrobe 2 gaun/kebaya",
            "Free baju casual",
            "Outdoor dan Indoor",

            "2 Pembesaran 40x60 plus frame",
            "Semua file copy",
            "Free Prewedding clip",
          ],
        },
        {
          name: "Outdoors Semarang",
          price: 4000000,
          features: [
            "Outdoor 2 lokasi",
            "Mua profesional",
            "2 Photographer",
            "Wadrobe 1 gaun/kebaya",
            "Free baju casual",

            "2 Pembesaran 40x60 plus frame",
            "Semua file copy",
            "Free Prewedding clip",
            "4R x 10 Print",
          ],
        },
        {
          name: "Outdoors Jogjakarta",
          price: 4300000,
          features: [
            "Outdoor 2 lokasi",
            "Mua profesional",
            "2 Photographer",
            "Wadrobe 1 gaun/kebaya",
            "Free baju casual",

            "2 Pembesaran 40x60 plus frame",
            "Semua file copy",
            "Free Prewedding clip",
            "4R x 10 Print",
          ],
        },
      ],
    },
    {
      type: "group",
      name: "Indoors",
      items: [
        {
          name: "Indoors Special Promo",
          price: 750000,
          features: [
            "1 Konsep Studio",
            "4r X10 Lembar",
            "20 - 35 File ( Langsung Jadi )",
            "Semua File Copy",
          ],
        },
        {
          name: "Indoors Exlusive",
          price: 1500000,
          features: [
            "2 Konsep Studio",
            "2 Pembesaran 40 X 60 + Frame",
            "20 - 30 File Edit",
            "Semua File Copy",
          ],
        },
        {
          name: "Indoors Gold",
          price: 2000000,
          features: [
            "2 Konsep Studio",
            "2 Pembesaran 40 X 60 + Frame",
            "Prewedding Clip Indoor",
            "Free Baju Casual",
            "30 - 40 File Edit",
            "Semua File Copy",
          ],
        },
      ],
      notes: [
        "Harga Tidak Termasuk Mua & Wardrobe",
        "Booking Min. 1 Minggu Sebelum Foto",
      ],
    },
    {
      type: "group",
      name: "With Ken Ayu",
      notes: ["Harga belum termasuk akomodasi izin dilokasi"],
      items: [
        {
          name: "Premium with Ken Ayu",
          price: 2000000,
          features: [
            "Indoor (1 konsep)",
            "MUA Profesional by Ken ayu",
            "2 Photographer",
            "1 gaun/kebaya by Ken ayu",
            "1 Cetak 16RS+Frame",
          ],
        },
        {
          name: "Exlusive with Ken Ayu",
          price: 2500000,
          features: [
            "Indoor(1 konsep)/Outdoor(1 lokasi sekitar studio)",
            "MUA Profesional by Ken ayu",
            "2 Photographer",
            "1 gaun/kebaya by Ken ayu",
            "FREE baju casual (milik pribadi)",
            "2 cetakan 16RS + Frame",
          ],
        },
        {
          name: "Gold with Ken Ayu",
          price: 3500000,
          features: [
            "Indoor/Outdoor (Lokasi sekitar studio)",
            "2 Konsep + FREE 1 Konsep casual",
            "MUA Profesional by Ken ayu",
            "2 Photographer",
            "2 gaun/kebaya by Ken ayu",
            "baju casual (milik pribadi)",
            "2 cetakan 16RS + Frame",
            "Semua file dalam Flashdisk",
            "FREE PREWEDDING CLIP",
          ],
        },
        {
          name: "SSK with Ken Ayu",
          price: 4500000,
          features: [
            "SEMARANG/SOLO/KARANGANYAR",
            "outdoor (2 lokasi)",
            "MUA Profesional by Ken ayu",
            "2 Photographer & Videographer",
            "1 gaun/kebaya by Ken ayu",
            "FREE baju casual (milik pribadi)",
            "1 Assistant MUA standby",
            "2 cetakan 16RS + Frame",
            "Video Prewedding Clip",
            "Semua file dalam Flashdisk",
          ],
        },
        {
          name: "Jogjakarta with Ken Ayu",
          price: 5000000,
          features: [
            "outdoor (2 lokasi)",
            "MUA Profesional",
            "2 Photographer & Videographer",
            "1 gaun/kebaya by ken ayu",
            "FREE baju casual (milik pribadi)",
            "1 Assistant MUA Standby",
            "2 cetakan 16RS + Frame",
            "Video Prewedding Clip",
            "4R X 10 Print",
            "Semua file dalam Flashdisk",
          ],
        },
      ],
    },
    {
      type: "group",
      name: "With Ayuk Project",
      notes: ["Harga belum termasuk akomodasi izin dilokasi"],
      items: [
        {
          name: "With Ayuk Project",
          price: 2000000,
          features: [
            "Indoor (1 konsep)",
            "MUA Profesional by Ayuk Project",
            "2 Photographer",
            "1 gaun/kebaya by Ayuk Project",
            "1 cetak 16RS + Frame",
          ],
        },
        {
          name: "Exlusive with Ayuk Project",
          price: 2500000,
          features: [
            "Indoor (1 konsep)/Outdoor (1 lokasi sekitar studio)",
            "MUA Profesional by Ayuk Project",
            "2 Photographer",
            "1 gaun/kebaya by Ayuk Project",
            "FREE baju casual (milik pribadi)",
            "2 cetak 16RS + Frame",
          ],
        },
        {
          name: "Gold with Ayuk Project",
          price: 3500000,
          features: [
            "Indoor/Outdoor (Lokasi sekitar studio)",
            "2 konsep + FREE 1 konsep casual",
            "MUA Profesional by Ayuk Project",
            "2 Photographer",
            "2 gaun/kebaya by Ayuk Project",
            "baju casual (milik pribadi)",
            "2 cetak 16RS + Frame",
            "Semua file dalam Flashdisk",
            "FREE prewedding clip",
          ],
        },
      ],
    },
    {
      type: "group",
      name: "With Rama Kurniawan",
      notes: ["Harga belum termasuk akomodasi izin dilokasi"],
      items: [
        {
          name: "With Rama Kurniawan",
          price: 2000000,
          features: [
            "Indoor (1 konsep)",
            "MUA Profesional by Rama Kurniawan",
            "2 Photographer",
            "1 gaun/kebaya by Rama Kurniawan",
            "1 cetak 16RS + Frame",
          ],
        },
        {
          name: "Exlusive with Rama Kurniawan",
          price: 2500000,
          features: [
            "Indoor (1 konsep)/Outdoor (1 lokasi sekitar studio)",
            "MUA Profesional by Rama Kurniawan",
            "2 Photographer",
            "1 gaun/kebaya by Rama Kurniawan",
            "FREE baju casual (milik pribadi)",
            "2 cetak 16RS + Frame",
          ],
        },
        {
          name: "Gold with Rama Kurniawan",
          price: 3500000,
          features: [
            "Indoor/Outdoor (Lokasi sekitar studio)",
            "2 konsep + FREE 1 konsep casual",
            "MUA Profesional by Rama Kurniawan",
            "2 Photographer",
            "2 gaun/kebaya by Rama Kurniawan",
            "baju casual (milik pribadi)",
            "2 cetak 16RS + Frame",
            "Semua file dalam Flashdisk",
            "FREE prewedding clip",
          ],
        },
      ],
    },
    {
      type: "group",
      name: "With Thata Silvia",
      items: [
        {
          name: "With Thata Silvia",
          price: 2000000,
          features: [
            "Indoor (1 konsep)",
            "MUA Profesional by Thata Silvia",
            "2 Photographer",
            "1 gaun/kebaya by Thata Silvia",
            "1 cetak 16RS + Frame",
            "Semua file dalam Flashdisk",
          ],
        },
      ],
    },
  ],
};
