/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeddingCoverageIndexRouteImport } from './routes/wedding-coverage/index'
import { Route as StudioPhotographyIndexRouteImport } from './routes/studio-photography/index'
import { Route as ProductShootIndexRouteImport } from './routes/product-shoot/index'
import { Route as PreweddingShootIndexRouteImport } from './routes/prewedding-shoot/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as DebugIndexRouteImport } from './routes/debug/index'
import { Route as AboutUsIndexRouteImport } from './routes/about-us/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingCoverageIndexRoute = WeddingCoverageIndexRouteImport.update({
  id: '/wedding-coverage/',
  path: '/wedding-coverage/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPhotographyIndexRoute = StudioPhotographyIndexRouteImport.update({
  id: '/studio-photography/',
  path: '/studio-photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductShootIndexRoute = ProductShootIndexRouteImport.update({
  id: '/product-shoot/',
  path: '/product-shoot/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreweddingShootIndexRoute = PreweddingShootIndexRouteImport.update({
  id: '/prewedding-shoot/',
  path: '/prewedding-shoot/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsIndexRoute = AboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/debug/': typeof DebugIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/prewedding-shoot/': typeof PreweddingShootIndexRoute
  '/product-shoot/': typeof ProductShootIndexRoute
  '/studio-photography/': typeof StudioPhotographyIndexRoute
  '/wedding-coverage/': typeof WeddingCoverageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsIndexRoute
  '/debug': typeof DebugIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/prewedding-shoot': typeof PreweddingShootIndexRoute
  '/product-shoot': typeof ProductShootIndexRoute
  '/studio-photography': typeof StudioPhotographyIndexRoute
  '/wedding-coverage': typeof WeddingCoverageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us/': typeof AboutUsIndexRoute
  '/debug/': typeof DebugIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/prewedding-shoot/': typeof PreweddingShootIndexRoute
  '/product-shoot/': typeof ProductShootIndexRoute
  '/studio-photography/': typeof StudioPhotographyIndexRoute
  '/wedding-coverage/': typeof WeddingCoverageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us/'
    | '/debug/'
    | '/gallery/'
    | '/prewedding-shoot/'
    | '/product-shoot/'
    | '/studio-photography/'
    | '/wedding-coverage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/debug'
    | '/gallery'
    | '/prewedding-shoot'
    | '/product-shoot'
    | '/studio-photography'
    | '/wedding-coverage'
  id:
    | '__root__'
    | '/'
    | '/about-us/'
    | '/debug/'
    | '/gallery/'
    | '/prewedding-shoot/'
    | '/product-shoot/'
    | '/studio-photography/'
    | '/wedding-coverage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsIndexRoute: typeof AboutUsIndexRoute
  DebugIndexRoute: typeof DebugIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PreweddingShootIndexRoute: typeof PreweddingShootIndexRoute
  ProductShootIndexRoute: typeof ProductShootIndexRoute
  StudioPhotographyIndexRoute: typeof StudioPhotographyIndexRoute
  WeddingCoverageIndexRoute: typeof WeddingCoverageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-coverage/': {
      id: '/wedding-coverage/'
      path: '/wedding-coverage'
      fullPath: '/wedding-coverage/'
      preLoaderRoute: typeof WeddingCoverageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-photography/': {
      id: '/studio-photography/'
      path: '/studio-photography'
      fullPath: '/studio-photography/'
      preLoaderRoute: typeof StudioPhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-shoot/': {
      id: '/product-shoot/'
      path: '/product-shoot'
      fullPath: '/product-shoot/'
      preLoaderRoute: typeof ProductShootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prewedding-shoot/': {
      id: '/prewedding-shoot/'
      path: '/prewedding-shoot'
      fullPath: '/prewedding-shoot/'
      preLoaderRoute: typeof PreweddingShootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/': {
      id: '/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us/': {
      id: '/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof AboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsIndexRoute: AboutUsIndexRoute,
  DebugIndexRoute: DebugIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PreweddingShootIndexRoute: PreweddingShootIndexRoute,
  ProductShootIndexRoute: ProductShootIndexRoute,
  StudioPhotographyIndexRoute: StudioPhotographyIndexRoute,
  WeddingCoverageIndexRoute: WeddingCoverageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
